# Load data in dataframe

In [1]:
#cells inserted to imported modules
import types
import pandas as pd
import matplotlib.pyplot as plt
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_00523e55e0a5426b9e750aa61c129a54 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id=<**REPLACE_WITH_YOUR_IBM_API_KEY_ID**>,
    ibm_auth_endpoint="https://iam.ng.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_00523e55e0a5426b9e750aa61c129a54.get_object(Bucket=<**REPLACE_WITH_YOUR_BUCKET_ID**>,Key='BK_18v1.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dfbk = pd.read_csv(body)
dfbk.head()

/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (19,20,22,23,24,25,26,64,65,80) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Borough,Block,Lot,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,...,ZMCode,Sanborn,TaxMap,EDesigNum,APPBBL,APPDate,PLUTOMapID,FIRM07_FLAG,PFIRM15_FLAG,Version
0,BK,1,1,302,21.0,NaN,13.0,33.0,11201.0,L118,...,NaN,302 007,30101.0,NaN,3.000010e+09,11/26/2013,1,1.0,1.0,18V1
1,BK,1,50,302,21.0,2000.0,13.0,33.0,11201.0,L118,...,NaN,302 007,30101.0,E-231,0.000000e+00,NaN,1,1.0,1.0,18V1
2,BK,1,7501,302,21.0,2000.0,13.0,33.0,11201.0,L118,...,NaN,302 007,30101.0,NaN,3.000010e+09,03/04/2016,1,1.0,1.0,18V1
3,BK,3,1,302,21.0,3002.0,13.0,33.0,11201.0,L118,...,NaN,302 007,30101.0,NaN,0.000000e+00,NaN,1,1.0,1.0,18V1
4,BK,3,5,302,21.0,NaN,13.0,33.0,11201.0,L118,...,NaN,302 007,30101.0,NaN,0.000000e+00,NaN,4,1.0,1.0,18V1

In [2]:
# @hidden_cell
# The following code contains the credentials for a file in your IBM Cloud Object Storage.
# You might want to remove those credentials before you share your notebook.
credentials_1 = {
    'IAM_SERVICE_ID': ****,
    'IBM_API_KEY_ID': <**REPLACE_WITH_YOUR_IBM_API_KEY_ID**>,
    'ENDPOINT': 'https://s3-api.us-geo.objectstorage.service.networklayer.com',
    'IBM_AUTH_ENDPOINT': 'https://iam.ng.bluemix.net/oidc/token',
    'BUCKET': <**REPLACE_WITH_YOUR_BUCKET_ID**>,
    'FILE': 'SI_18v1.csv'
}

In [3]:
client_cred = ibm_boto3.client(service_name='s3',
ibm_api_key_id=<**REPLACE_WITH_YOUR_IBM_API_KEY_ID**>,
ibm_auth_endpoint='https://iam.ng.bluemix.net/oidc/token',
config=Config(signature_version='oauth'),
endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

# Load the dataset in a dataframe

In [4]:
nycdf = pd.read_csv("https://data.cityofnewyork.us/resource/fhrw-4uyv.csv?$limit=100000000&Agency=HPD&$select=created_date,unique_key,complaint_type,incident_zip,incident_address,street_name,address_type,city,resolution_description,borough,latitude,longitude,closed_date,location_type,status", nrows=10000000, parse_dates=['created_date','closed_date'])

In [102]:
nycdf.head()

,created_date,unique_key,complaint_type,incident_zip,incident_address,street_name,address_type,city,resolution_description,borough,latitude,longitude,closed_date,location_type,status
0,2019-12-14 16:55:57,45158002,HEAT/HOT WATER,11235.0,2750 HOMECREST AVENUE,HOMECREST AVENUE,ADDRESS,BROOKLYN,The complaint you filed is a duplicate of a co...,BROOKLYN,40.584298,-73.956290,NaT,RESIDENTIAL BUILDING,Open
1,2019-12-14 22:53:21,45160691,HEAT/HOT WATER,11355.0,45-15 COLDEN STREET,COLDEN STREET,ADDRESS,Flushing,The complaint you filed is a duplicate of a co...,QUEENS,40.750501,-73.823002,NaT,RESIDENTIAL BUILDING,Open
2,2019-12-14 16:56:02,45163196,HEAT/HOT WATER,10001.0,436 WEST 34 STREET,WEST 34 STREET,ADDRESS,NEW YORK,The following complaint conditions are still o...,MANHATTAN,40.753980,-73.997744,NaT,RESIDENTIAL BUILDING,Open
3,2019-12-11 21:05:30,45133435,HEAT/HOT WATER,10006.0,1 LIBERTY PLAZA,LIBERTY PLAZA,ADDRESS,NEW YORK,The Department of Housing Preservation and Dev...,MANHATTAN,40.709430,-74.011102,2019-12-13 16:45:25,RESIDENTIAL BUILDING,Closed
4,2019-12-14 06:45:53,45157328,HEAT/HOT WATER,10468.0,2319 LORING PLACE NORTH,LORING PLACE NORTH,ADDRESS,BRONX,The following complaint conditions are still o...,BRONX,40.862075,-73.908133,NaT,RESIDENTIAL BUILDING,Open

Data is loaded on monday the 16th of december 2019 when this is written

In [85]:
nycdf.describe()

         unique_key  incident_zip      latitude     longitude
count  5.959628e+06  5.878948e+06  5.878974e+06  5.878974e+06
mean   2.940224e+07  1.074733e+04  4.075415e+01 -7.391987e+01
std    7.787041e+06  5.130484e+02  9.087644e-02  5.686382e-02
min    1.562973e+07  1.000100e+04  4.049934e+01 -7.425312e+01
25%    2.285201e+07  1.045200e+04  4.067112e+01 -7.395200e+01
50%    2.921510e+07  1.046900e+04  4.075677e+01 -7.392249e+01
75%    3.563759e+07  1.122400e+04  4.083953e+01 -7.389025e+01
max    4.516346e+07  1.234500e+04  4.091287e+01 -7.370079e+01

# Question 2:
Should the Department of Housing Preservation and Development of New York City focus on any particular set of boroughs, ZIP codes, or street (where the complaints are severe) for the specific type of complaints you identified in response to Question 1?

# Subset data with the complainttypes

In [86]:
compl=nycdf['complaint_type'].value_counts()
compl

HEAT/HOT WATER            1218988
HEATING                    887869
PLUMBING                   708364
GENERAL CONSTRUCTION       500863
UNSANITARY CONDITION       447183
PAINT - PLASTER            361257
PAINT/PLASTER              344715
ELECTRIC                   306042
NONCONST                   260890
DOOR/WINDOW                203484
WATER LEAK                 191800
GENERAL                    149797
FLOORING/STAIRS            136746
APPLIANCE                  111801
HPD Literature Request      52830
SAFETY                      51046
OUTSIDE BUILDING             7099
ELEVATOR                     6634
Unsanitary Condition         5499
CONSTRUCTION                 5078
General                      1163
Safety                        424
STRUCTURAL                     16
Plumbing                       11
AGENCY                          9
VACANT APARTMENT                8
Outside Building                6
Appliance                       4
Mold                            1
Electric                        1
Name: complaint_type, dtype: int64

From the above df it is clear that HEAT/HOT WATER and HEATING are the two main areas to focus on.

In [87]:
#Lets set the complainttypes to only be HEAT/HOT WATER and HEATING
array = ["HEAT/HOT WATER", "HEATING"]
heatdf=nycdf.loc[nycdf['complaint_type'].isin(array)]
heatdf.head()

,created_date,unique_key,complaint_type,incident_zip,incident_address,street_name,address_type,city,resolution_description,borough,latitude,longitude,closed_date,location_type,status
0,2019-12-14 16:55:57,45158002,HEAT/HOT WATER,11235.0,2750 HOMECREST AVENUE,HOMECREST AVENUE,ADDRESS,BROOKLYN,The complaint you filed is a duplicate of a co...,BROOKLYN,40.584298,-73.956290,NaT,RESIDENTIAL BUILDING,Open
1,2019-12-14 22:53:21,45160691,HEAT/HOT WATER,11355.0,45-15 COLDEN STREET,COLDEN STREET,ADDRESS,Flushing,The complaint you filed is a duplicate of a co...,QUEENS,40.750501,-73.823002,NaT,RESIDENTIAL BUILDING,Open
2,2019-12-14 16:56:02,45163196,HEAT/HOT WATER,10001.0,436 WEST 34 STREET,WEST 34 STREET,ADDRESS,NEW YORK,The following complaint conditions are still o...,MANHATTAN,40.753980,-73.997744,NaT,RESIDENTIAL BUILDING,Open
3,2019-12-11 21:05:30,45133435,HEAT/HOT WATER,10006.0,1 LIBERTY PLAZA,LIBERTY PLAZA,ADDRESS,NEW YORK,The Department of Housing Preservation and Dev...,MANHATTAN,40.709430,-74.011102,2019-12-13 16:45:25,RESIDENTIAL BUILDING,Closed
4,2019-12-14 06:45:53,45157328,HEAT/HOT WATER,10468.0,2319 LORING PLACE NORTH,LORING PLACE NORTH,ADDRESS,BRONX,The following complaint conditions are still o...,BRONX,40.862075,-73.908133,NaT,RESIDENTIAL BUILDING,Open

Lets start by exploring borough, zip and adresses to find the highest counts:

In [88]:
heatbor = heatdf['borough'].value_counts()
heatbor.head()

BRONX          590857
BROOKLYN       562875
MANHATTAN      414051
Unspecified    282917
QUEENS         238161
Name: borough, dtype: int64

In [89]:
heatzip = heatdf['incident_zip'].value_counts()
heatzip.head()

11226.0    67748
10467.0    64788
10458.0    64108
10468.0    56882
10453.0    56681
Name: incident_zip, dtype: int64

In [90]:
heatadd = heatdf['incident_address'].value_counts()
heatadd.head()

34 ARDEN STREET          13846
89-21 ELMHURST AVENUE    10977
3810 BAILEY AVENUE        7113
1025 BOYNTON AVENUE       5779
9511 SHORE ROAD           4572
Name: incident_address, dtype: int64

Bronx and brooklyn are the highest values for complaints. Since this is quite a large area, it could be beneficial to also consider the zipcodes

In [91]:
bronx = heatdf.loc[nycdf['borough'] == 'BRONX']

In [92]:
bronxzip = bronx['incident_zip'].value_counts()
bronxzip.head()

10467.0    55905
10458.0    55728
10468.0    49362
10453.0    48801
10452.0    42346
Name: incident_zip, dtype: int64

This seems to support our findings, since the most complaints from bronzipcodes are also in the overall highest zipcodes. The top zipcode 11226.0 is missing in the bronx area. We need to find this zipcode as well.

In [99]:
zip = heathotdf['incident_zip']==11226.0
zipdf = heathotdf[zip]
zipdf.head()

,created_date,unique_key,complaint_type,incident_zip,incident_address,street_name,address_type,city,resolution_description,borough,latitude,longitude,closed_date,location_type,status
50,2019-12-14 22:55:10,45157931,HEAT/HOT WATER,11226.0,2620 BEVERLY ROAD,BEVERLY ROAD,ADDRESS,BROOKLYN,The complaint you filed is a duplicate of a co...,BROOKLYN,40.644915,-73.952351,NaT,RESIDENTIAL BUILDING,Open
60,2019-12-14 06:42:00,45160507,HEAT/HOT WATER,11226.0,390 OCEAN AVENUE,OCEAN AVENUE,ADDRESS,BROOKLYN,The following complaint conditions are still o...,BROOKLYN,40.653419,-73.961651,NaT,RESIDENTIAL BUILDING,Open
226,2019-12-14 21:58:47,45158215,HEAT/HOT WATER,11226.0,15 WOODRUFF AVENUE,WOODRUFF AVENUE,ADDRESS,BROOKLYN,The following complaint conditions are still o...,BROOKLYN,40.652743,-73.965161,NaT,RESIDENTIAL BUILDING,Open
249,2019-12-14 04:48:39,45157374,HEAT/HOT WATER,11226.0,370 EAST 31 STREET,EAST 31 STREET,ADDRESS,BROOKLYN,The following complaint conditions are still o...,BROOKLYN,40.641809,-73.947640,NaT,RESIDENTIAL BUILDING,Open
261,2019-12-14 13:01:26,45161325,HEAT/HOT WATER,11226.0,40 EAST 17 STREET,EAST 17 STREET,ADDRESS,BROOKLYN,The complaint you filed is a duplicate of a co...,BROOKLYN,40.650006,-73.964175,NaT,RESIDENTIAL BUILDING,Open

This is a Brooklyn area, that could also have focus in these complainttypes

The top adress is not near the amount of complaintes regarding borough or zipcode, but it could be interesting to see where the street is situated

In [100]:
add = heathotdf['incident_address']=='34 ARDEN STREET'
adddf = heathotdf[add]
adddf.head()

,created_date,unique_key,complaint_type,incident_zip,incident_address,street_name,address_type,city,resolution_description,borough,latitude,longitude,closed_date,location_type,status
32228,2019-12-13 07:56:22,45149692,HEAT/HOT WATER,10040.0,34 ARDEN STREET,ARDEN STREET,ADDRESS,NEW YORK,The complaint you filed is a duplicate of a co...,MANHATTAN,40.861937,-73.927146,2019-12-14 16:30:36,RESIDENTIAL BUILDING,Closed
36193,2019-12-11 06:47:17,45139803,HEAT/HOT WATER,10040.0,34 ARDEN STREET,ARDEN STREET,ADDRESS,NEW YORK,The Department of Housing Preservation and Dev...,MANHATTAN,40.861937,-73.927146,2019-12-11 07:31:09,RESIDENTIAL BUILDING,Closed
36658,2019-12-10 07:40:49,45122855,HEAT/HOT WATER,10040.0,34 ARDEN STREET,ARDEN STREET,ADDRESS,NEW YORK,The Department of Housing Preservation and Dev...,MANHATTAN,40.861937,-73.927146,2019-12-11 07:31:09,RESIDENTIAL BUILDING,Closed
38170,2019-12-08 00:58:04,45106773,HEAT/HOT WATER,10040.0,34 ARDEN STREET,ARDEN STREET,ADDRESS,NEW YORK,The Department of Housing Preservation and Dev...,MANHATTAN,40.861937,-73.927146,2019-12-09 20:56:35,RESIDENTIAL BUILDING,Closed
40018,2019-12-09 00:12:53,45107347,HEAT/HOT WATER,10040.0,34 ARDEN STREET,ARDEN STREET,ADDRESS,NEW YORK,The Department of Housing Preservation and Dev...,MANHATTAN,40.861937,-73.927146,2019-12-09 20:56:35,RESIDENTIAL BUILDING,Closed

From the findings provided above it seems that the most reasonable place for the Department of Housing Preservation and Development of New York City to focus on is:

<p>Bronx Borough <br />
<p>Zipcode 11226.0 in Brooklyn <br />
<p>34 Arden Street